name: Build Debian Docker image (Essentia + MusicNN)

on:
  push:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/build-docker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image (amd64)
        run: |
          cd docker
          docker build --platform=linux/amd64 -t z-music-dev .